# Generated by Django 4.2.7 on 2024-01-01 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEvents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='availability',
        ),
        migrations.AlterField(
            model_name='user',
            name='nif',
            field=models.BigIntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000000, message='NIF must be exactly 9 digits'), django.core.validators.MaxValueValidator(999999999, message='NIF must be exactly 9 digits')]),
        ),
    ]
